[package]
name = "rust-sharing-cli"
version = "0.1.0"
authors = ["Josiah Bull <josiah.bull7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="2.33.3"
reqwest="0.11.3"
tokio = { version = "1.5.0", features = ["full"] }
clipboard = "0.5.0"
serde = {version = "1.0.126", features=["derive"]}
serde_json = "1.0.64"