[package]
name = "cli"
version = "0.1.0"
authors = ["Josiah Bull <josiah.bull7@gmail.com>"]
edition = "2021"

[dependencies]
utils = { git = "https://github.com/file-share-platform/utils", default-features = false, features = ["hex"]}
ws-com-framework = { path="../../ws-com-framework" }
config = { path = "../config", features = ["sync"] }
database = { path = "../database" }

clap = "2.33.3"
whoami = "1.1.2"
chrono = { version = "0.4" }