[package]
name = "cli"
version = "0.1.0"
authors = ["Josiah Bull <josiah.bull7@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { git = "https://github.com/file-share-platform/utils", default-features = false, features = ["hex"]}
ws-com-framework = { git="https://github.com/file-share-platform/ws-com-framework", default-features = false, rev= "7260559" }
config = { path = "../config" }
database = { path = "../database" }

clap = "2.33.3"
whoami = "1.1.2"
chrono = { version = "0.4" }