[package]
name = "database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws-com-framework= { git="https://github.com/file-share-platform/ws-com-framework", default-features = false, rev= "550d7fe" }
diesel = { version = "1.4.8", default-features = false, features = ["chrono", "sqlite"] }
config = { path = "../config" }
chrono = { version = "0.4" }