websocket_address = "ws://localhost:8000/api/v1"
server_address = "http://localhost:8000/api/v1"
file_store_location = "${CONFIG_DIR}/riptide/hard_links"
max_upload_attempts = 10
size_limit_bytes = 2147483648
default_share_time_hours = 48
reconnect_delay_minutes = 15