websocket_address = "wss://localhost:8080"
server_address = "https://localhost:8080"
database_location = "${CONFIG_DIR}/shares.db"
file_store_location = "${CONFIG_DIR}/hard_links"
max_upload_attempts = 10
size_limit_bytes = 2147483648
reconnect_delay_minutes = 15
