---
name: pre-release

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install protoc
        run: wget https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0/protoc-3.20.0-linux-x86_64.zip &&
          unzip protoc-3.20.0-linux-x86_64.zip &&
          sudo cp -r include/* /usr/local/include &&
          sudo cp bin/protoc /usr/bin/

      - name: Build Project
        run: cargo build --release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          title: "Dev Build"
          files: |
            license
            readme.md
            target/release/cli
            target/release/agent
