---
name: release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install upx
        run: sudo apt-get install upx

      - name: Install protoc
        run: wget https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0/protoc-3.20.0-linux-x86_64.zip &&
          unzip protoc-3.20.0-linux-x86_64.zip &&
          sudo cp -r include/* /usr/local/include &&
          sudo cp bin/protoc /usr/bin/

      - name: Install nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build Project
        run: cargo +nightly build -Z build-std=std,panic_abort --target x86_64-unknown-linux-gnu --profile production

      - name: Compress Project
        run: |
          upx --lzma --best target/x86_64-unknown-linux-gnu/production/riptide_agent
          upx --lzma --best target/x86_64-unknown-linux-gnu/production/riptide_cli
          mv target/x86_64-unknown-linux-gnu/production/riptide_agent agent
          mv target/x86_64-unknown-linux-gnu/production/riptide_cli cli
          mv target/x86_64-unknown-linux-gnu/production/shell_completions completions
          mv completions/_riptide completions/_riptide.zsh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            license
            readme.md
            cli
            agent
            shell_completions.zip
            completions/_riptide.zsh
            completions/riptide.bash
            completions/riptide.fish
            completions/riptide.elv

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          ref: latest
          description: The latest release for the dds application
          force-branch: false
